In [8]:
from pathlib import Path
import torch
import numpy as np
import matplotlib.pyplot as plt
import json
import pandas as pd

Entire the desired output_directory, model_name, and metric we care about. Then run all the code below

In [9]:
output_dir = 'outputs_edges'

output_dir = Path('/data/vision/polina/users/marcusbl/bin_class') / output_dir

model_name = 'model_loss'
metrics = ['auc', 'acc']

Parse results into Pandas DF

In [10]:
results = []

for test_dir in output_dir.iterdir():
    for run_dir in test_dir.iterdir():
        if not run_dir.is_dir():
            continue

        with open(run_dir / 'test_info' / 'metric_info.json') as f:
            metric_info = json.load(f)

        flat = {
            (model, metric): value
            for model, metrics in metric_info.items()
            for metric, value in metrics.items()
        }

        results.append({
            "test": test_dir.name,
            "run": run_dir.name,
            **flat
        })

df = pd.DataFrame(results).set_index(["test", "run"])

df.columns = pd.MultiIndex.from_tuples(df.columns)
df = df.sort_index(axis=1).sort_index()

In [11]:
df['model_auc']

                   acc    auc  epoch     f1   fn   fp    fpr   loss   prec  \
test       run
drop_all1  run0  0.857  0.884     -1  0.588  149   51  0.046  0.331  0.737
           run1  0.807  0.899     -1  0.692   66  204  0.198  0.418  0.598
           run2  0.770  0.888     -1  0.766   82  351  0.321  0.568  0.669
           run3  0.750  0.868     -1  0.601   21  142  0.279  0.556  0.464
           run4  0.878  0.847     -1  0.551   32   56  0.088  0.344  0.491
drop_all2  run0  0.914  0.905     -1  0.700   54   24  0.032  0.244  0.791
           run1  0.928  0.847     -1  0.505   38   13  0.020  0.241  0.667
           run2  0.816  0.894     -1  0.667   78  217  0.177  0.372  0.576
           run3  0.802  0.918     -1  0.599   28  208  0.210  0.424  0.458
           run4  0.831  0.898     -1  0.689   56   64  0.123  0.422  0.675
drop_eval1 run0  0.890  0.904     -1  0.706  107   47  0.042  0.290  0.797
           run1  0.769  0.867     -1  0.642   79  245  0.238  0.448  0.543
           run2  0.743  0.860     -1  0.733  127  358  0.327  0.493  0.650
           run3  0.773  0.879     -1  0.619   24  124  0.244  0.477  0.492
           run4  0.867  0.822     -1  0.538   30   66  0.103  0.363  0.459
drop_eval2 run0  0.913  0.925     -1  0.721   43   36  0.047  0.227  0.739
           run1  0.937  0.849     -1  0.536   38    7  0.011  0.239  0.788
           run2  0.819  0.879     -1  0.641  114  176  0.144  0.364  0.595
           run3  0.825  0.910     -1  0.608   42  167  0.169  0.411  0.492
           run4  0.859  0.912     -1  0.708   68   32  0.062  0.364  0.791
regular1   run0  0.847  0.884     -1  0.654  191   88  0.064  0.357  0.750
           run1  0.747  0.850     -1  0.629  101  354  0.269  0.527  0.521
           run2  0.721  0.827     -1  0.722  211  471  0.349  0.598  0.653
           run3  0.787  0.883     -1  0.672   30  149  0.238  0.489  0.551
           run4  0.867  0.828     -1  0.559   72   54  0.068  0.333  0.597
regular2   run0  0.889  0.911     -1  0.698   81   49  0.052  0.292  0.754
           run1  0.896  0.877     -1  0.625   44   53  0.066  0.351  0.604
           run2  0.833  0.872     -1  0.674  203  142  0.094  0.401  0.715
           run3  0.762  0.895     -1  0.657   47  320  0.279  0.505  0.524
           run4  0.844  0.908     -1  0.751   75   70  0.110  0.373  0.758

                 recall    tn   tp    tpr
test       run
drop_all1  run0   0.490  1060  143  0.490
           run1   0.822   826  304  0.822
           run2   0.896   743  710  0.896
           run3   0.854   367  123  0.854
           run4   0.628   582   54  0.628
drop_all2  run0   0.628   735   91  0.628
           run1   0.406   634   26  0.406
           run2   0.791  1009  295  0.791
           run3   0.863   781  176  0.863
           run4   0.704   456  133  0.704
drop_eval1 run0   0.634  1064  185  0.634
           run1   0.786   785  291  0.786
           run2   0.840   736  665  0.840
           run3   0.833   385  120  0.833
           run4   0.651   572   56  0.651
drop_eval2 run0   0.703   723  102  0.703
           run1   0.406   640   26  0.406
           run2   0.694  1050  259  0.694
           run3   0.794   822  162  0.794
           run4   0.640   488  121  0.640
regular1   run0   0.580  1281  264  0.580
           run1   0.792   961  385  0.792
           run2   0.808   877  887  0.808
           run3   0.859   477  183  0.859
           run4   0.526   740   80  0.526
regular2   run0   0.649   893  150  0.649
           run1   0.648   753   81  0.648
           run2   0.637  1364  356  0.637
           run3   0.882   826  352  0.882
           run4   0.745   566  219  0.745

Average/Variance for desired metrics over all runs for the desired model

In [12]:
m = df[model_name]

stats = m.groupby(level='test').agg(['mean', 'var'])

stats = stats.sort_values(by=('auc', 'mean'), ascending=False)

stats[[(metric, stat) for metric in metrics for stat in ['mean', 'var']]]

               auc               acc
              mean       var    mean       var
test
drop_all2   0.9014  0.000679  0.8922  0.001174
drop_eval2  0.8884  0.000868  0.8796  0.001962
regular2    0.8786  0.000692  0.8450  0.001539
drop_all1   0.8738  0.000366  0.8452  0.001609
drop_eval1  0.8644  0.000109  0.8262  0.002497
regular1    0.8576  0.000385  0.8046  0.002318