In [25]:
from tqdm import tqdm
from pathlib import Path
import json
import pandas as pd
import numpy as np

In [26]:
root_dir = Path('/data/vision/polina/users/marcusbl/data')

In [28]:
stack_info = [] # dict of {total: #, pos: #, neg: #}
person_info = [] # dict of {stacks_cnt: #}
for person_path in tqdm(list(Path(root_dir).iterdir()), "Loading People Data: "):

    for stack_path in (person_path).iterdir():
        info_dir = stack_path / 'clean'

        # 1) Load Labels
        with open(info_dir / 'labels.json', 'r') as f:
            label_map: dict = json.load(f) # scan_num -> label

        # 2) Get Dicoms, Niftis, Masks (Width, Height, Scans)
        dicom_stack_path = info_dir / 'dicoms.npy'
        nifti_stack_path = info_dir / 'niftis.npy'
        mask_stack_path  = info_dir / 'masks.npy'
        
        pos_count = np.sum(list(label_map.values())).item()
        stack_info.append(
            {
                "total": len(label_map),
                "pos": pos_count, 
                "neg": len(label_map) - pos_count,
            }
        )
    
    person_info.append({"stack_cnt": len(list(((person_path).iterdir())))})

Loading People Data: 100%|██████████| 30/30 [00:00<00:00, 52.48it/s]

# Person Info

In [35]:
person_df = pd.DataFrame(person_info)
person_df.describe()

       stack_cnt
count  30.000000
mean   10.233333
std     5.556502
min     1.000000
25%     6.000000
50%     8.500000
75%    14.000000
max    23.000000

# Stack Info

In [43]:
stack_df = pd.DataFrame(stack_info)
stack_df['pos_ratio'] = stack_df['pos'] / stack_df['total']
stack_df

     total  pos  neg  pos_ratio
0       39    0   39   0.000000
1       17    3   14   0.176471
2       16    4   12   0.250000
3       16   14    2   0.875000
4       16    9    7   0.562500
..     ...  ...  ...        ...
302     34    4   30   0.117647
303     10    8    2   0.800000
304     34    3   31   0.088235
305     10    4    6   0.400000
306     33    1   32   0.030303

[307 rows x 4 columns]

In [38]:
stack_df.describe()

            total         pos         neg   pos_ratio
count  307.000000  307.000000  307.000000  307.000000
mean    27.755700    7.019544   20.736156    0.278117
std     11.294437    7.270201   12.066757    0.261516
min      1.000000    0.000000    0.000000    0.000000
25%     20.000000    2.000000   12.000000    0.083333
50%     28.000000    5.000000   20.000000    0.200000
75%     36.000000    9.000000   30.000000    0.384615
max     51.000000   40.000000   51.000000    1.000000